name: flutter_neat_and_clean_calendar
description: >-
  Simple and clean flutter calendar with ability to  slide up/down to show
  weekly/monthly calendar.  Fork of
  https://pub.dev/packages/flutter_clean_calendar
version: 0.3.16+36
homepage: "https://github.com/ziad4347/flutter_neat_and_clean_calendar"

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  macos_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null
